PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX edam:<http://edamontology.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?entity ?property ?value  WHERE {
    
    VALUES ?property { edam:next_id }
    #retrieve the last ID
    <http://edamontology.org> ?property ?value .
    
    #match all IDs
    ?entity rdf:type owl:Class .    
    BIND(strafter(str(?entity), "_") AS ?id) .

    #retrieve the ones that should me lower than the last id
    FILTER (?id >= ?value)
} 


