PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX edam:<http://edamontology.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
#Query aim = “check for missing wikipedia link in topic ”

SELECT DISTINCT ?entity ?label ?seealso WHERE {
    ?entity rdfs:subClassOf+ <http://edamontology.org/topic_0003> .
    ?entity rdfs:label ?label .
    
    FILTER NOT EXISTS {
        ?entity rdfs:seeAlso ?seealso .
        FILTER (regex(str(?seealso), "wikipedia", "i")) .
    }
}

