PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX edam:<http://edamontology.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?entity ?label ?property ?entity2 ?label2 ?property2 ?value WHERE { 
    VALUES ?property {
                      oboInOwl:hasDefinition
                      oboInOwl:hasExactSynonym
                      oboInOwl:hasNarrowSynonym
                      #oboInOwl:hasBroadSynonym
                      #rdfs:comment
                      rdfs:label
                        }
    VALUES ?property2 {
                      oboInOwl:hasDefinition
                      oboInOwl:hasExactSynonym
                      oboInOwl:hasNarrowSynonym
                      #oboInOwl:hasBroadSynonym
                      #rdfs:comment
                      #rdfs:label
                        }
        
    
    ?entity a owl:Class . 
    ?entity2 a owl:Class . 
    ?entity ?property ?value .
    
    ?entity2 ?property2 ?value .

    #?entity2 ?property2 ?value2 .    
    #FILTER ( UCASE(str(?value)) = UCASE(str(?value2)) )      
    
    FILTER (?entity != ?entity2)
    ?entity rdfs:label ?label .
    ?entity2 rdfs:label ?label2 .
    
}
ORDER BY ?value


