PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX edam:<http://edamontology.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?entity ?property ?label ?property_subs_edam WHERE {
    {
    VALUES ?property { oboInOwl:hasDefinition
                       rdfs:subClassOf
                       edam:created_in
                       oboInOwl:inSubset
                       rdfs:label
                        }
    ?entity a owl:Class .
    FILTER NOT EXISTS {?entity owl:deprecated true .}
    ?entity rdfs:label ?label .

    FILTER NOT EXISTS {?entity ?property ?value .}
    }
    UNION
    {
    VALUES ?property { oboInOwl:inSubset
                        }
    FILTER NOT EXISTS {?entity ?property <http://purl.obolibrary.org/obo/edam#edam> .}
    }
    #should specify thet there shoul be 2 subset, one edam and one different with a value "not in"?
}
ORDER BY ?entity

