PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX edam:<http://edamontology.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?entity ?property ?property2 ?value ?label WHERE {
    VALUES ?property {oboInOwl:hasDefinition
                      oboInOwl:hasExactSynonym
                      oboInOwl:hasNarrowSynonym
                      oboInOwl:hasBroadSynonym
                      rdfs:comment
                      rdfs:label
                      edam:documentation
                        }
    VALUES ?property2 {oboInOwl:hasDefinition
                      oboInOwl:hasExactSynonym
                      oboInOwl:hasNarrowSynonym
                      oboInOwl:hasBroadSynonym
                      rdfs:comment
                      rdfs:label
                      edam:documentation
                        }

    ?entity a owl:Class . 
    ?entity ?property ?value .
    ?entity ?property2 ?value2 .
#    FILTER (?value = ?value2)
    FILTER ( UCASE(str(?value)) = UCASE(str(?value2)) )

    FILTER (?property != ?property2)    
    ?entity rdfs:label ?label .
  
}
ORDER BY ?value
