PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX edam:<http://edamontology.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?entity ?target ?label ?property
WHERE {
    VALUES ?property { edam:has_topic
                       edam:has_input
                       edam:has_output
                       edam:is_format_of
                       edam:is_identifier_of
                       
                        }
    ?entity ?p ?value .
    #{?entity rdfs:subClassOf+ edam:operation_0004 .}
    #UNION
    #{
    #?entity rdfs:subClassOf+ edam:data_0006 .
    #}
    ?entity rdfs:label ?label .
    ?entity rdfs:subClassOf ?restriction . 
    ?restriction rdf:type owl:Restriction ; 
            owl:onProperty ?property  ; 
            owl:someValuesFrom ?target.
    ?target owl:deprecated ?deprecated . 
    FILTER (?deprecated = true)
}
ORDER BY ?entity 