
name: cseologue test

on: 
  push:

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        pip install -r caseologue_python/requirements.txt

    - name: run bash
      if: always()
      run: |
        cd ./caseologue_python
        while read line; do 
                ./script.sh $line;
        done < test_name_list.txt


# duplicate all not tested, too long to run