name: caseologue

on: [push, pull_request, workflow_dispatch, workflow_call]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        pip install -r caseologue/requirements.txt
        cd caseologue/
        wget https://raw.githubusercontent.com/edamontology/edamontology/main/EDAM_dev.owl
    - name: run 
      run: |
        cd caseologue/
        EDAM_PATH=./EDAM_dev.owl python3 caseologue.py -e -E
     
    # - name: Print output
    #   if: always()
    #   run: |
    #     cat output_caseologue.tsv 

    - name: Archive tests output
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: output_caseologue
        path: caseologue/output_caseologue.tsv