name: caseologue python

on: 
  workflow_call:
    inputs:
      edam_path: 
        type: string
        required: true
      caseologue_options:
        type: string

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v3
      # with:
        # This will automatically check out the branch that triggered the workflow
        # within the current repository.
        # repository: ${{ github.repository }}
        # ref: ${{ github.ref }}
    
    - name: download artifacts
      uses: actions/download-artifact@v3
      with:
        name: input_ontology 
    - name: Display structure of files
      run: ls -R
  
    - name: Install requirements
      run: |
        pip install -r caseologue_python/requirements.txt

    - name: run 
      run: |
        cd caseologue_python/
        printf "\n_____________________________________________________________________________________________\n\nThe following debug table is archived as an artifact called 'output_caseologue'\n_____________________________________________________________________________________________\n\n"
        EDAM_PATH=${{inputs.edam_path}} python3 caseologue.py ${{inputs.caseologue_options}}

    - name: Archive test outputs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: output_caseologue
        path: caseologue_python/output_caseologue.tsv
