name: caseologue python

on: 
  workflow_call:
    inputs:
      edam_path: 
        type: string
        default: '$( wget https://raw.githubusercontent.com/edamontology/edamontology/main/EDAM_dev.owl)EDAM_dev.owl'
      caseologue_options:
        type: string

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        pwd
        echo "GITHUB.ACTION_REPOSITORY=${{ GITHUB.ACTION_REPOSITORY }}"
        pip install -r ${{GITHUB.ACTION_REPOSITORY }}/caseologue/requirements.txt

    - name: run 
      run: |
        EDAM_PATH=${{inputs.edam_path}} python3 ${{ github.action_path }}/../../caseologue/caseologue.py ${{inputs.caseologue_options}}
     
    # - name: Print output
    #   if: always()
    #   run: |
    #     cat output_caseologue.tsv 

    - name: Archive tests output
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: output_caseologue
        path: caseologue/output_caseologue.tsv