name: caseologue python

on: 
  workflow_call:
    inputs:
      edam_path: 
        type: string
        required: true
      caseologue_options:
        type: string

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2
      with: 
        repository: edamontology/caseologue
    
    - name: download artifacts
      uses: actions/download-artifact@v3
      with:
        name: input_ontology 
    - name: Display structure of files
      run: ls -R
  
    - name: Install requirements
      run: |
        pip install -r caseologue_python/requirements.txt

    - name: run 
      run: |
        cd caseologue_python/
        printf "\n_____________________________________________________________________________________________\n\nFollowing debug table can be found as a tsv file at the bottom of the summary of this job\n_____________________________________________________________________________________________"
        EDAM_PATH=${{inputs.edam_path}} python3 caseologue.py ${{inputs.caseologue_options}}
     
    # - name: Print output
    #   if: always()
    #   run: |
    #     cat caseologue_python/output_caseologue.tsv 

    - name: Archive tests output
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: output_caseologue
        path:
          - caseologue_python/output_caseologue.tsv
          - caseologue_python/output_caseologue_timing.tsv
