name: EDAM-VALIDATION 

on: [workflow_dispatch]

jobs:
  
  edam-custom:
    uses: edamontology/edam-validation/.github/workflows/edam-custom.yml@main

  report:
    uses: edamontology/edam-validation/.github/workflows/robot_report.yml@main

  reason:
    uses: edamontology/edam-validation/.github/workflows/robot_reason.yml@main