name: EDAM-CUSTOM

on: [push, pull_request, workflow_dispatch, workflow_call]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        pip install -r edam-custom/requirements.txt
        cd edam-custom/
        wget https://raw.githubusercontent.com/edamontology/edamontology/main/EDAM_dev.owl
    - name: run 
      run: |
        cd edam-custom/
        EDAM_PATH=./EDAM_dev.owl python3 edam-custom.py -e -E
     
    # - name: Print output
    #   if: always()
    #   run: |
    #     cat output_edam-custom.tsv 

    - name: Archive tests output
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: output_edam-custom
        path: edam-custom/output_edam-custom.tsv