name: EDAMCI

on: [push, pull_request, workflow_dispatch]

jobs:
  
  job1_edamci:

      runs-on: ubuntu-latest

      steps:
        
        - uses: actions/checkout@v2

        - name: Install requirements
          run: |
            pip install -r edamci/requirements.txt
            cd edamci/
            wget https://raw.githubusercontent.com/edamontology/edamontology/main/EDAM_dev.owl
        - name: run 
          run: |
            cd edamci/
            EDAM_PATH=./EDAM_dev.owl python3 edamci.py -e -E

        - name: Archive tests output
          if: always()
          uses: actions/upload-artifact@v2
          with:
            name: output_edamci
            path: edamci/output_edamci.tsv