name: EDAM-VALIDATION 

on: [workflow_dispatch]

jobs:
  
  job1_edamci:
    
      runs-on: ubuntu-latest

      steps:

        - uses: /home/runner/work/edamontology/edamontology/edam-validation/.github/workflows/run_edamci.yml
