name: EDAM-VALIDATION ALL 

on: [workflow_dispatch]

jobs:
  
  job1_edamci:
    
      runs-on: ubuntu-latest

      steps:
        
        - uses: actions/checkout@v2

        - name: Install requirements edamci 
          run: |
            pip install -r edamci/requirements.txt
            cd edamci/
            wget https://raw.githubusercontent.com/edamontology/edamontology/main/EDAM_dev.owl
        
        - name: run edamci
          run: |
            cd edamci/
            EDAM_PATH=./EDAM_dev.owl python3 edamci.py -e -E

        - name: Archive edamci tests output
          if: always()
          uses: actions/upload-artifact@v2
          with:
            name: output_edamci
            path: edamci/output_edamci.tsv

  job2_robot_reasonner:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Set up 
        run: |
          cd robot/ 
          wget https://raw.githubusercontent.com/edamontology/edamontology/main/EDAM_dev.owl

      - name: run reason
        run: |
          cd robot/ 
          export PATH=/home/runner/work/edamontology/edamontology/edam-validation/robot:$PATH
          java -jar robot.jar reason --reasoner ELK   --input EDAM_dev.owl -v   

  job3_robot_report:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Set up 
        run: |
          cd robot/ 
          wget https://raw.githubusercontent.com/edamontology/edamontology/main/EDAM_dev.owl

      - name: run report 
        if: always()
        run: |
          cd robot/
          export PATH=:/home/runner/work/edamontology/edamontology/edam-validation/robot:$PATH
          java -jar robot.jar report --input EDAM_dev.owl --output report_profile.tsv --profile report_queries.txt
          more report_profile.tsv

      - name: Print report output
        if: always()
        run: |
          more ./robot/report_profile.tsv


      - name: Archive Robot report tests
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: robot_report_profile
          path: ./robot/report_profile.tsv