name: ROBOT

on:
  [push, pull_request, workflow_dispatch]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Set up 
      run: |
        cd robot/ 
        wget https://raw.githubusercontent.com/edamontology/edamontology/main/EDAM_dev.owl

    - name: run reason
      run: |
        cd robot/ 
        export PATH=/home/runner/work/edamontology/edamontology/edam-validation/robot:$PATH
        java -jar robot.jar reason --reasoner ELK   --input EDAM_dev.owl -v 

