name: ROBOT report

on:
  [push, pull_request, workflow_dispatch]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Set up 
      run: |
        cd robot/ 
        wget https://raw.githubusercontent.com/edamontology/edamontology/main/EDAM_dev.owl

    - name: run report 
      if: always()
      run: |
        cd robot/
        export PATH=:/home/runner/work/edamontology/edamontology/edam-validation/robot:$PATH
        java -jar robot.jar report --input EDAM_dev.owl --output report_profile.tsv --profile report_queries.txt
        more report_profile.tsv

    - name: Print report output
      if: always()
      run: |
        more /robot/report_profile.tsv


    - name: Archive Robot report tests
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: robot_report_profile
        path: /robot/report_profile.tsv
