name: ROBOT

on:
  [push, pull_request, workflow_dispatch]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Set up 
      run: |
        git clone https://github.com/edamontology/edamverify.git

    - name: run reason
      run: |
        export PATH=/home/runner/work/edamontology/edamontology/edamverify/robot:$PATH
        robot reason --reasoner ELK   --input EDAM_dev.owl -v 

